<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="eaadapter" nsURI="http://eaadapter" nsPrefix="eaadapter">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The package for the EA metamodel.&lt;br>&#xD;&#xA;&lt;code>EARepository&lt;/code> is the root element for all EA models.&lt;br>&#xD;&#xA;&lt;/div>"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EAAttribute" eSuperTypes="#//abstracthierachy/EAModifiableElement #//abstracthierachy/EAClassifierIDLong">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;An attribute of the element.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For more detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="allowDuplicates" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="container" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scale" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="precision" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperBound" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//EAElement"
        transient="true" eOpposite="#//EAElement/attributes"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Attribute"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValues" upperBound="-1"
        eType="#//EAAttributeTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAAttributeTag" eSuperTypes="#//abstracthierachy/EATaggedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Tagged Value.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_AttributeTag"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAConnector" eSuperTypes="#//abstracthierachy/EATypedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A connector represents an association between two EAElements.&lt;br>&#xD;&#xA;The type  defines what kind of connector it is. Examples are: &lt;code>Association, Generalization, Dependency&lt;/code>.&lt;br>&#xD;&#xA;&lt;br>&#xD;&#xA;The &lt;code>connector&lt;/code> has a &lt;code>client&lt;/code> (source) and a &lt;code>supplier&lt;/code> (target).&#xD;&#xA;&lt;i>For more detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectorID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSpec" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtualInheritance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionEvent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionAction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="transitionGuard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="routeStyle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceNo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Connector"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValues" upperBound="-1"
        eType="#//EAConnectorTag" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="client" lowerBound="1"
        eType="#//EAElement" unsettable="true" eOpposite="#//EAElement/connectors">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Reference to the target EAElement of this connector.&lt;br>&#xD;&#xA;&lt;b>Note:&lt;/b> Take care that this reference will always be valid, otherwise the EA takes care of it and 'garbage collects' it.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplier" lowerBound="1"
        eType="#//EAElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//EAConnectorConstraint" containment="true" eOpposite="#//EAConnectorConstraint/connector"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clientEnd" eType="#//EAConnectorEnd"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clientID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="supplierID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong">
      <eAnnotations/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eventFlags" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="styleEx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supplierEnd" eType="#//EAConnectorEnd"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAConnectorTag" eSuperTypes="#//abstracthierachy/EATaggedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Tagged Value.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_ConntectorTag"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAElement" eSuperTypes="#//abstracthierachy/EAClassifierIDLong #//abstracthierachy/EAOwnedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;An Element can, for instance,  be a class, an interface or a UML Note.&lt;br>&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifierName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifierType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="complexity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="difficulty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="extensionPoints" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genlinks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="genfile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gentype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subtype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tablespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//EAElement"
        transient="true" eOpposite="#//EAElement/elements"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="package" eType="#//EAPackage"
        transient="true" eOpposite="#//EAPackage/elements">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The parent package.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
        eType="#//EAAttribute" containment="true" eOpposite="#//EAAttribute/element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectors" upperBound="-1"
        eType="#//EAConnector" containment="true" eOpposite="#//EAConnector/client">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The containment reference &lt;code>connectors&lt;/code> contains all connectors from the &#xD;&#xA;Enterprise Architect model which have the current element as their 'source'. &lt;br>&#xD;&#xA;Thus, connectors which have the current element as &lt;code>supplier&lt;/code> are not contained!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//EAElement" containment="true" eOpposite="#//EAElement/element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="methods" upperBound="-1"
        eType="#//EAMethod" containment="true" eOpposite="#//EAMethod/element"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValues" upperBound="-1"
        eType="#//EATaggedValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Element"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parentID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allConnectors" upperBound="-1"
        eType="#//EAConnector" changeable="false" volatile="true" transient="true"
        derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The containment reference &lt;code>allConnectors&lt;/code> contains all connectors from the &#xD;&#xA;Enterprise Architect model which references or are referenced by the current element.&#xD;&#xA;&lt;br>Note that the containment reference is a derived attribute!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isActive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//EAConstraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metaType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAMethod" eSuperTypes="#//abstracthierachy/EAModifiableElement #//abstracthierachy/EAClassifierIDLong">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;An operation of the element it belongs to.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="returnIsArray" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="code" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="throws" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPure" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRoot" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLeaf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isQuery" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSynchronized" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isAbstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="concurrency" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="element" eType="#//EAElement"
        transient="true" eOpposite="#//EAElement/methods"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Method"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//EAParameter" containment="true" eOpposite="#//EAParameter/method"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="taggedValues" upperBound="-1"
        eType="#//EAMethodTag" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAMethodTag" eSuperTypes="#//abstracthierachy/EATaggedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Tagged Value.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_MethodTag"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAPackage" eSuperTypes="#//abstracthierachy/EAAbstractPackage">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A package in EA is a container for other elements.&lt;br>&#xD;&#xA;A package can, for instance, be a UML package.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="diagnostic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
      <eParameters name="context">
        <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//EAElement" containment="true" eOpposite="#//EAElement/package">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Set of contained elements.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="packages" upperBound="-1"
        eType="#//EAPackage" containment="true" eOpposite="#//EAPackage/superPackage">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Subpackages of this package.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superPackage" eType="#//EAPackage"
        eOpposite="#//EAPackage/packages">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The parent package.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Package"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The stereotype attribute is part of an object of type &lt;code>EAElement&lt;/code> which is referenced by each package.&lt;br>&#xD;&#xA;This object causes a lot of trouble because it has the same &lt;i>guid&lt;/i> as the package, so a wrapper getter and setter are generated by the code generation templates.&lt;br>&#xD;&#xA;As a consequence, the stereotype attribute can be used as a usual attribute."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAParameter" eSuperTypes="#//abstracthierachy/EAClassifierIDLong">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Parameter of a method.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="default" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="position" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" eType="#//EAMethod"
        transient="true" eOpposite="#//EAMethod/parameters"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Parameter"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EARepository">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Root object for an EA project.&lt;br>&#xD;&#xA;This object takes care of the link between the EMF model and the EA project.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eOperations name="load" eExceptions="#//datatypes/Exception">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This is the method which initializes the model.&lt;br>&#xD;&#xA;The method basically operates in two sequential steps:&lt;br>&#xD;&#xA;&lt;b>1) &lt;/b> Initialize all Packages and Elements&lt;br>&#xD;&#xA;&lt;b>2) &lt;/b> Initialize all Connectors&lt;br>&#xD;&#xA;This two step approach is necessary since all classes and packages must be present&#xD;&#xA;before the connectors can be added.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eOperations>
    <eOperations name="getEANamedElementByGUID" eType="#//abstracthierachy/EANamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This method returns an &lt;code>EANamedElement&lt;/code> by its global unique identifier &lt;code>GUID&lt;/code>.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
      <eParameters name="guid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getEAElementByGUID" eType="#//EAElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This method returns an &lt;code>EAElement&lt;/code> by its global unique identifier &lt;code>GUID&lt;/code>.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
      <eParameters name="guid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getEANamedElementByID" upperBound="-1" eType="#//abstracthierachy/EANamedElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This method returns a list of &lt;code>EANamedElement&lt;/code> identified by its id &lt;code>ID&lt;/code>.&lt;br>&#xD;&#xA;Note that an element's &lt;code>ID&lt;/code> is only unique within its current model. Hence, it is possible that an&#xD;&#xA;&lt;code>ID&lt;/code> can appear more than once.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eOperations name="getEAElementByID" upperBound="-1" eType="#//EAElement">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;This method returns a list of &lt;code>EAElement&lt;/code> identified by its id &lt;code>ID&lt;/code>.&lt;br>&#xD;&#xA;Note that an element's &lt;code>ID&lt;/code> is only unique within its current model. Hence, it is possible that an&#xD;&#xA;&lt;code>ID&lt;/code> can appear more than once.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
      <eParameters name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_Repository"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="file" eType="#//datatypes/File">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Specify the Enterprise Architect project file here.&lt;br>&#xD;&#xA;An absolut path is required!&lt;br>&#xD;&#xA;TODO: Implement support for relative paths and eclipse resource URIs.&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="models" upperBound="-1"
        eType="#//EAPackage" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EATaggedValue" eSuperTypes="#//abstracthierachy/EATaggedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Tagged Value.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_TaggedValue"
        transient="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;DO NOT TOUCH THIS! This attributed is used as a link to the Enterprise Architect and is managed internally only!&#xD;&#xA;&lt;/div>"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAConnectorEnd" eSuperTypes="#//abstracthierachy/EANamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Connector End.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TaggedValues" upperBound="-1"
        eType="#//EARoleTag" containment="true" eOpposite="#//EARoleTag/connectorEnd"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="end" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="role" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="roleNote" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="containment" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregation" eType="#//datatypes/T_ConnectorAggregation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNavigable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isChangable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_ConnectorEnd"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAConnectorConstraint" eSuperTypes="#//abstracthierachy/EANamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Connector Constraint.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectorID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connector" eType="#//EAConnector"
        eOpposite="#//EAConnector/constraints"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_ConnectorConstraint"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EARoleTag" eSuperTypes="#//abstracthierachy/EANamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;A Role Tag.&#xD;&#xA;&lt;br>&lt;br>&lt;i>For detailled documentation see &lt;a href='http://www.sparxsystems.com.au/EAUserGuide/index.html' target='_blank'>EA User Guide&lt;/a>!&lt;/i>&#xD;&#xA;&lt;/div>"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseClass" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="elementGUID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyGUID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectorEnd" eType="#//EAConnectorEnd"
        eOpposite="#//EAConnectorEnd/TaggedValues"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="eaLink" eType="#//datatypes/T_RoleTag"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EAConstraint" eSuperTypes="#//abstracthierachy/EANamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="datatypes" nsURI="http://eaadapter.datatypes" nsPrefix="eaadapter.datatypes">
    <eClassifiers xsi:type="ecore:EDataType" name="T_Attribute" instanceClassName="org.sparx.Attribute"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_AttributeTag" instanceClassName="org.sparx.AttributeTag"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Connector" instanceClassName="org.sparx.Connector"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_ConnectorEnd" instanceClassName="org.sparx.ConnectorEnd"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_ConntectorTag" instanceClassName="org.sparx.ConnectorTag"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Element" instanceClassName="org.sparx.Element"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Method" instanceClassName="org.sparx.Method"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_MethodTag" instanceClassName="org.sparx.MethodTag"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Package" instanceClassName="org.sparx.Package"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Parameter" instanceClassName="org.sparx.Parameter"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_Repository" instanceClassName="org.sparx.Repository"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_TaggedValue" instanceClassName="org.sparx.TaggedValue"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_ConnectorConstraint" instanceClassName="org.sparx.ConnectorConstraint"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EDataType" name="T_RoleTag" instanceClassName="org.sparx.RoleTag"
        serializable="false"/>
    <eClassifiers xsi:type="ecore:EEnum" name="T_ConnectorAggregation">
      <eLiterals name="None"/>
      <eLiterals name="Shared" value="1"/>
      <eLiterals name="Composite" value="2"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EDataType" name="Exception" instanceClassName="java.lang.Exception"/>
  </eSubpackages>
  <eSubpackages name="abstracthierachy" nsURI="http://eaadapter.abstracthierachy"
      nsPrefix="eaadapter.abstracthierachy">
    <eClassifiers xsi:type="ecore:EClass" name="EAAbstractPackage" abstract="true"
        interface="true" eSuperTypes="#//abstracthierachy/EAVersiondElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="codePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="flags" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isModel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAClassifierIDLong" abstract="true"
        interface="true" eSuperTypes="#//abstracthierachy/EATypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="classifierID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAModifiableElement" abstract="true"
        interface="true" eSuperTypes="#//abstracthierachy/EATypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isConst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EANamedElement" abstract="true" interface="true">
      <eOperations name="validate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
        <eParameters name="diagnostic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDiagnosticChain"/>
        <eParameters name="context">
          <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
            <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
          </eGenericType>
        </eParameters>
      </eOperations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="name">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;The name of the EA element.&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="notes" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Each EA element may have a note.&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="guid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true">
        <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
          <details key="documentation" value="&lt;div class='userdoc'>&#xD;&#xA;Each element of the EA has a Global Unique IDendifier!&lt;br>&#xD;&#xA;This guid is used as an ID for the EMF model as well!&lt;br>&#xD;&#xA;Unfortunately, it is a readonly attribute for EA elements.&lt;br>&#xD;&#xA;&lt;b>Important: This attribute is set automatically if the adapter is initialized via &lt;code>initializeAdapter&lt;/code>!&lt;/b>&#xD;&#xA;&lt;/div>"/>
        </eAnnotations>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAOwnedElement" abstract="true" interface="true"
        eSuperTypes="#//abstracthierachy/EAVersiondElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="author" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLocked" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAStereotypedElement" abstract="true"
        interface="true" eSuperTypes="#//abstracthierachy/EANamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotype" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="stereotypeEx" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EATaggedElement" abstract="true" interface="true"
        eSuperTypes="#//abstracthierachy/EANamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EATypedElement" abstract="true" interface="true"
        eSuperTypes="#//abstracthierachy/EAStereotypedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EAVersiondElement" abstract="true"
        interface="true" eSuperTypes="#//abstracthierachy/EANamedElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
